//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butterfly.Service.Salary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryComponentDef
    {
        public SalaryComponentDef()
        {
            this.CompType = 0;
            this.CompCalcMethod = 0;
            this.CompCalcValue = 0m;
        }
    
        public string CompId { get; set; }
        public string CompName { get; set; }
        public string CompDesc { get; set; }
        public int CompType { get; set; }
        public int CompCalcMethod { get; set; }
        public decimal CompCalcValue { get; set; }
    }
}
