//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butterfly.Service.Salary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryComponents
    {
        public SalaryComponents()
        {
            this.CompValue = 0m;
            this.CompType = 0;
        }
    
        public string CompId { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> CompValue { get; set; }
        public Nullable<int> CompType { get; set; }
        public string CompDescription { get; set; }
    }
}
